package com.example.demoprodata.in.pojo;

public class DemoPro001 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_pro_001.id
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_pro_001.name
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_pro_001.id
     *
     * @return the value of demo_pro_001.id
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_pro_001.id
     *
     * @param id the value for demo_pro_001.id
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_pro_001.name
     *
     * @return the value of demo_pro_001.name
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_pro_001.name
     *
     * @param name the value for demo_pro_001.name
     *
     * @mbg.generated Sun Sep 11 20:51:00 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}